# Stage 1
FROM ubuntu:22.04 AS base

# Set non-interactive mode to avoid prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary dependencies
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test
RUN set -e; \
    for i in 1 2 3 4 5; do \
        echo "Attempt $i: Updating and installing..."; \
        apt-get update --allow-releaseinfo-change && \
        apt-get install -y --no-install-recommends --fix-missing \
            build-essential \
            python3 \
            python3-distutils \
            g++-10 \
            make \
            curl \
            git \
            pkg-config \
            libssl-dev \
            libffi-dev \
            libgmp-dev \
            libtool \
            autoconf \
            automake \
            cmake \
            wget \
            xz-utils \
            unzip \
            vim \
        && break || \
        echo "Attempt $i failed! Waiting 15 seconds..." && sleep 15; \
    done
RUN rm -rf /var/lib/apt/lists/*

# Set g++ 10 as the default
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100

# Copy local Node.js source into the image
WORKDIR /usr/src/node
COPY . .

RUN ./configure --shared-openssl --experimental-enable-pointer-compression --openssl-conf-name 'openssl_conf'
RUN make -j4 install DESTDIR=./node-install

CMD ["bash"]
